Pass context to new exception in ``replace_exceptions`` decorator.
